### ISSUE TITLE
Be able to dynamically link with any PSA Crypto C shared library

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-psa-crypto#1]
Ideally this crate should not be responsible for compiling the PSA Crypto implementation (such as Mbed Crypto) but the user should do it and instantiate this wrapper with a path to the `.so`.

The dynamic loading can be done [`libloading`](https://crates.io/crates/libloading).

**Comment by hug-dev** [comment]
About the headers: since PSA API is specified and versioned we should be able to generate the Rust bindings ourselves. Either by fetching the headers from a standard location, by sourcing the bindings in our code or by source the PSA header files themselves.

**Comment by ionut-arm** [comment]
I think it makes sense to have an `include` folder in our code that's just a copy of the "original" ones, submodules would probably be overkill.

**Comment by hug-dev** [comment]
Sadly I realised that because of lot of types defined in the API are opaque (implementation-defined), the `include` folder of the PSA Crypto implementation is needed in order to compile. That means the following things:

* the two inputs of this crate will be the PSA Crypto implementation library path + the `psa` include folder path
* dynamic loading is impossible because the types can not be resolved at runtime

**Comment by hug-dev** [comment]
> dynamic loading is impossible because the types can not be resolved at runtime

I meant it like it is impossible to dynamically link with any PSA Crypto implementation but it would be possible to dynamically link with a set of known implementations.

**Comment by hug-dev** [comment]
Closing as not possible right now.
