### ISSUE TITLE
Discuss type/module naming

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-psa-crypto#17]
I'm a bit weary of some of our naming conventions. We adopt the "no prefix/sufix" format for not including the module name in type or function names. 

For example, we have `psa_crypto::types::key` which has types related to key attributes within it. I'd say this module (and its contents) could lead to confusion and/or conflicts for a couple of reasons:
* the module doesn't actually contain a `Key` type or anything of the sort - the closest would probably be `Id` which is an opaque handler for key stored elsewhere, so from that point of view the module name isn't accurate
* at least some of the types within the module have very vague names (mostly talking about `Id` and `Type` here); I agree that not all types should be fully named (e.g. `KeyPolicy`), but the overall effect of not using more specific names falls on users of the crate; if you know/see the `use psa_crypto::types::key::Type` then you'll find it easy to understand something like `Type::from(...)`; but if you're in the middle of a file and stumble across that, you have to look it up and then remember what that `Type` type represents; this puts a burden on the users to either rename the type on import, or keep it in mind while coding - the more types we do this with, the worse it gets; (also, imagine if all libraries did this and there were 3 `Type`s and 2`Id`s)

I've only looked through the standard library to get a feel for how we could tackle this and most of the types there seem to exclude prefixes or suffixes most of the time, but for example `std::thread` contains both `Thread` and `ThreadId`. My suggestion would be to prefix or suffix the names that are way too vague, leaving the other ones to follow convention. 

Take a look at the original PR that added the `module_name_repetitions` lint and especially at Martin Carton's comments: https://github.com/rust-lang/rust-clippy/pull/994

**Comment by hug-dev** [comment]
I guess those Clippy rules look good on paper but in practice for new users it might be difficult to understand what is `Type`, `Id`, `generate`, `destroy`, etc...
Most of it was a systematic translation of the C naming:
* `psa_key_type_t` -> `key::Type`
* `psa_key_id_t` -> `key::Id`
* etc
