### ISSUE TITLE
Conversion to `Status` seems wrong

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-psa-crypto#24]
Currently the conversion `From<psa_crypto_sys::psa_status_t> for Status` converts any unsupported integer to a `GenericError` - I think that's not entirely correct as it aliases an error occuring in the crate with one relayed by the linked library. 

The correct thing to do would be to have `TryFrom` and return a crate-specific error for anything outside of the recognised codes, and the correct enum variant for the correct ones. However I do get that `TryFrom` is not actually available without `std` so maybe we should have a method implemented straight on `Status` when `no-std` is on and the normal `TryFrom` when `std` is available.

**Comment by ionut-arm** [comment]
I'm assuming that as the library gets more complex there'll be more need for crate-internal errors

**Comment by hug-dev** [comment]
I agree that it is not ideal but it is also a way to simplify error handling with less types to unwrap for the caller. It's nice that conceptually only PSA Crypto 1.0.0 abstracted types are used and not our own.

**Comment by ionut-arm** [comment]
Agreed to leave as is for now, since it's not a huge problem. If something new pops up in the future, we can just reopen this
