### ISSUE TITLE
Design a good abstraction for key IDs

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-psa-crypto#4]
We need to find a nice way to represent the `psa_key_id_t` type in Rust.

**Comment by hug-dev** [comment]
The API defines a `psa_key_id_t` as:
```c
typedef uint32_t psa_key_id_t;
```
so I think it would be fine to have a:
```rust
struct KeyId(u32);
```
Because I think generally it would be great not to have to re-exports type from the `sys` crate.

With key IDs we want:
1. creating a `KeyId` with a specific number (there are restrictions on numbers allowed for persistent keys)
2. creating a Key ID with a random number

2 is complicated because then you need to remember the ID you have already picked in a set and making that set persistant through reboots. I think 2 is out of scope for now and  the core layer of the abstraction crate.

**Comment by egrimley-arm** [comment]
Reminder: `psa_open_key` and `psa_close_key` have been removed from 1.0.0 but are still present in Mbed TLS.

**Comment by hug-dev** [comment]
Ah yes, I forgot that Mbed TLS was not currently implementing exactly PSA Crypto 1.0.0
Should we target the same version as Mbed TLS does or 1.0.0 and implements the necessary mappings/logic?
The later might be more complicated for us but probably better for users over time.

**Comment by egrimley-arm** [comment]
Before doing any complicated mapping we should definitely check what the timetable is for Mbed TLS getting to 1.0.0.

**Comment by hug-dev** [comment]
Maybe @gilles-peskine-arm knows 😃?
Would you advise us to implement a PSA Crypto 1.0.0 interface or to follow the same one that Mbed TLS currently implements?
The first one is user-friendly but might be complicated for us, the second is easy for us but will potentially break the interface over time, depending on the timetable.

**Comment by gilles-peskine-arm** [comment]
You can see our [high-level roadmap](https://developer.trustedfirmware.org/w/mbed-tls/roadmap/) and our [current plan for this quarter](https://github.com/ARMmbed/mbedtls/projects/3). Catching up from API 1.0beta3 to API 1.0.0 is the epic [PSA Crypto: Update existing functionality to v1.0 spec](https://github.com/ARMmbed/mbedtls/projects/2#column-8733082). [Unifying `psa_key_handle_t` and `psa_key_id_t` and removing the need to call `psa_open_key` and `psa_close_key`](https://github.com/ARMmbed/mbedtls/issues/3265) is planned for June 2020.

I suggest designing a Rust API that doesn't have open/close, and that for the time being calls open/close under the hood each time a key is used (for multipart operations, you need to keep the key open until the operation finishes). Then, when Mbed TLS is updated, open/close will become essentially no-ops for backward compatibility, and the Rust wrappers can remove those calls.

**Comment by gilles-peskine-arm** [comment]
Key ids only have 30 bits. If you create keys with a random number, there's a non-negligible chance of collisions. Why would you do this anyway? You'd have to store the number somewhere.

**Comment by hug-dev** [comment]
That's great, thanks a lot for the pointers and the advice!
2. was not really clear but it was about storing all Key IDs created so far to have a function that returns a new, unused, Key ID so that the caller does not have to implement that logic themselves. We will probably not implement that for now.

**Comment by hug-dev** [comment]
Done as part as the release.
