### ISSUE TITLE
psa-crypto-sys test fail on i686

### ISSUE THREAD

**Issue by nullr0ute** [parallaxsecond/rust-psa-crypto#41]
One of the tests fails when run on i686:

<pre>
failures:
---- psa_crypto_binding::bindgen_test_layout_max_align_t stdout ----
thread 'psa_crypto_binding::bindgen_test_layout_max_align_t' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `24`: Size of: max_align_t', /builddir/build/BUILD/psa-crypto-sys-0.3.0/target/release/build/psa-crypto-sys-59266dd2c6e5c562/out/shim_bindings.rs:3:22153
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    psa_crypto_binding::bindgen_test_layout_max_align_t
test result: FAILED. 52 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
</pre>

**Comment by hug-dev** [comment]
Hello!

Thanks for reporting this! This seems to be a test generated by bindgen, after a quick google I have found a similar case [here](https://github.com/rust-av/aom-rs/commit/c65ca636b17c95152104fdf4c0fa20c08d3b3820) where they blocklisted the type.

I guess we could it as well as we do not need it?

**Comment by nullr0ute** [comment]
It passes on aarch64/x86_64/ppc64le/armv7. If the functionality isn't used I suspect blocking it is likely the best option.

**Comment by hug-dev** [comment]
@joechrisellis fixed this, it should work now 💯

**Comment by hug-dev** [comment]
Would you like us to do a patch release?
