### ISSUE TITLE
Exposing native types for key encodings

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-psa-crypto#53]
I was wondering if it makes sense to expose, potentially behind a feature flag, types that can be used for (de)serializing the various key types supported by PSA crypto. So, something like what we implement in Parsec, but for all types of keys.

This would help Parsec as well, and any users of the `psa-crypto` crate who want proper support for the "whole" PSA crypto interface.

**Comment by joechrisellis** [comment]
See [PR 56](https://github.com/parallaxsecond/rust-psa-crypto/pull/56). 🙂

**Comment by joechrisellis** [comment]
Closing following resolution of [PR 56](https://github.com/parallaxsecond/rust-psa-crypto/pull/56).
