### ISSUE TITLE
Delete const from pub const fn key_derivation

### ISSUE THREAD

**Issue by egrimley-arm** [parallaxsecond/rust-psa-crypto#64]
I can't build psa-crypto with version 1.45.2 of Rust because:
```
`match` is not allowed in a `const fn`
```

I can build it if I delete the `const` from `pub const fn key_derivation` here:

https://github.com/parallaxsecond/rust-psa-crypto/blob/master/psa-crypto/src/types/key_derivation.rs#L109

I don't think the `const` currently does anything useful so probably this change would be generally helpful.

**Comment by hug-dev** [comment]
This is [a feature that was added in Rust 1.46](https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html#const-fn-improvements).
@sbailey-arm added it in #58. Concerning its usefullness, it allows to be a bit faster at runtime to the cost of a larger binary.

Updating your Rust compiler might fix it, but if you think we should not have this requirement, we can probably remove it.

**Comment by egrimley-arm** [comment]
Does adding the `const` make this code faster with 1.46 (on a particular architecture)? If it does, then perhaps we should leave it. I'm a bit surprised, though. It sounds like inlining, and typically a compiler can work out for itself whether code can or should be inlined.

In general, depending on a feature in a compiler version that was released *on the previous day* (Aug 27-28) doesn't seem like a great idea. It's a bit of an obstacle for someone who just wants to build Parsec and then has to check out the other repo, fiddle with `[patch.crates-io]`, ...

NixOS doesn't have 1.46 yet, but it probably will in a few weeks.

**Comment by hug-dev** [comment]
> Does adding the const make this code faster with 1.46 (on a particular architecture)?

In this particular case I don't think the gain would be significant.

I am not sure of *all* differences between inlining and `const` functions but it seems like the [compiler guarantees](https://stackoverflow.com/a/60799649/4917222) are different.

I agree it was not a particular good idea to add this feature so soon after it is released for backward compatibility. I will make a PR to remove this one but it won't be available in Parsec until the next release...
