### ISSUE TITLE
What's the purpose of the "interface" feature?

### ISSUE THREAD

**Issue by dreemkiller** [parallaxsecond/rust-psa-crypto#66]
I'm attempting to us rust-psa-crypto to enable PSA Crypto bindings to a native PSA Crypto library in Web Assembly binaries compiled from Rust.

It looks like I want to remove compilation of shim.c, and replace it with a rust source file that has "extern C" for each of the API entrypoints.

However, I then found the "interface" feature, which *sounds* like what I'd want, but doesn't look like it in the code (but I'm still looking).

Anyway, I don't want to go down a stupid, work-heavy path, if you guys have already built in a mechanism that makes it easy.

**Comment by hug-dev** [comment]
Hello 👋 

> I'm attempting to us rust-psa-crypto to enable PSA Crypto bindings to a native PSA Crypto library in Web Assembly binaries compiled from Rust.

Just to make sure I understand it, you want to expose a PSA Crypto API from an implementation written in Rust so then if you compile everything you would have a PSA Crypto library basically?

The first use-case of this crate is to do the _reverse_: calling from Rust a PSA Crypto API implementation. However, and you are right, with the `interface` feature you might be able to do it!

The [`interface`](https://github.com/parallaxsecond/rust-psa-crypto/blob/master/psa-crypto/README.md#mbed-crypto-backing) feature makes this crate only contain the Rust-C bindings for the types (and not the operations) defined in PSA Crypto API. What it gives you essentially is a Rust native version of all PSA Crypto types and a conversion from them to the C version (which you can expose in the FFI).

So with this feature, you would be able to create a Rust library which:
* expose all of the PSA Crypto API through `extern "C"` functions
* inside the implementation of those `extern "C"` functions, you can use this crate to convert the types to the Rust native ones

Although, if my understanding of what you want to do is correct, you might as well look into the direction of creating a [PSA Secure Element driver](https://armmbed.github.io/mbed-crypto/psa/se/) (lins not up to date there). It might be easier to implement the Secure Element interface and plug it to Mbed Crypto than implementing the whole PSA Crypto interface.

This is actually what we do with the [Parsec Secure Element driver](https://github.com/parallaxsecond/parsec-se-driver)/

**Comment by dreemkiller** [comment]
Thanks, it does look like something involving the `interface `feature should work for me. However, I think you misunderstand what I'm trying to do, so for the sake of clarity, I'll try to explain.

We are enabling developers to be able to compile rust to web assembly that runs on our specific runtime. We would like them to be able to perform cryptographic operations using the PSA Crypto API. However, we do not want the PSA Crypto API implementation running in web assembly. Instead, we'd like to have the web assembly runtime provide that functionality. Thus, the web assembly binary would have `import`s for all of the PSA Crypto API functions (which would then be implemented in the runtime, probably by linking against mbedCrypto).
